--CREATE INICIAL DATABASE
--
--
--
--+----------------------------------------------------------------------------+
--|----------------------->>>>>>>>>>>>ENTITIES<<<<<<<<<<<<<<<<-----------------|
--+----------------------------------------------------------------------------+


--Student
CREATE TABLE TB_STUDENT(
   ID_STUDENT INT AUTO_INCREMENT PRIMARY KEY,
   NAME VARCHAR(255),
   BIRTHDATE DATE,
   ADDRESS VARCHAR(255),
   EMAIL VARCHAR(255) UNIQUE

);

--Professor
CREATE TABLE TB_PROFESSOR(
    ID_PROFESSOR INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    BIRTHDATE DATE,
    ADDRESS VARCHAR(255),
    EMAIL VARCHAR(255) UNIQUE

);

--Coordinator
CREATE TABLE TB_COORDINATOR(
    ID_COORDINATOR INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    BIRTHDATE DATE,
    ADDRESS VARCHAR(255),
    EMAIL VARCHAR(255) UNIQUE

);

--Classroom
CREATE TABLE TB_CLASSROOM(
    ID_CLASSROOM INT AUTO_INCREMENT PRIMARY KEY,
    SHIFT VARCHAR(255),
    LETTER VARCHAR(255),
    SEMESTER VARCHAR(255),

    ID_COURSE_FK INT,
    FOREIGN KEY (ID_COURSE_FK) REFERENCES TB_COURSE(ID_COURSE)

);

--Course
CREATE TABLE TB_COURSE(
    ID_COURSE INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    HOUR_TIME VARCHAR(255),

    ID_COORDINATOR_FK INT,
    ID_INSTITUTION_FK INT,

    FOREIGN KEY(ID_COORDINATOR_FK) REFERENCES TB_COORDINATOR(ID_COORDINATOR),
    FOREIGN KEY(ID_INSTITUTION_FK) REFERENCES TB_INSTITUTION(ID_INSTITUTION)

);

--Institution
CREATE TABLE TB_INSTITUTION(
    ID_INSTITUTION INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255)

);

--Invoice
CREATE TABLE TB_INVOICE(
    ID_INVOICE INT AUTO_INCREMENT PRIMARY KEY,
    AMOUNT DECIMAL(10,2),
    HOLDER VARCHAR(255),

    ID_STUDENT_FK INT,

    FOREIGN KEY(ID_STUDENT_FK) REFERENCES TB_STUDENT(ID_STUDENT)

);

--Subject
CREATE TABLE TB_SUBJECT(
    ID_SUBJECT INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    HOUR_TIME VARCHAR(255)

);

--
--
--
--+----------------------------------------------------------------------------+
--|------------------>>>>>>>>>>>>ASSOCIATION TABLES<<<<<<<<<<<<<<<<<-----------|
--+----------------------------------------------------------------------------+
--
--
--

--Subject_Average
CREATE TABLE TB_SUBJECT_AVERAGES(
    NOTA_1 DECIMAL(10,2),
    NOTA_2 DECIMAL(10,2),
    NOTA_3 DECIMAL(10,2),
    MEDIA DECIMAL(10,2) AS ((NOTA_1 + NOTA_2 + NOTA_3) / 3) STORED,

    ID_STUDENT_FK INT,
    ID_COURSE_FK INT,

    PRIMARY KEY(ID_STUDENT_FK, ID_COURSE_FK),
    FOREIGN KEY(ID_STUDENT_FK) REFERENCES TB_STUDENT(ID_STUDENT),
    FOREIGN KEY(ID_COURSE_FK) REFERENCES TB_COURSE(ID_COURSE)
);

--Report_Cards
CREATE TABLE TB_REPORT_CARDS(
    ID_REPORT_CARD INT AUTO_INCREMENT PRIMARY KEY,

    ID_STUDENT_FK INT,
    ID_COURSE_FK INT,

    FOREIGN KEY(ID_STUDENT_FK) REFERENCES TB_STUDENT(ID_STUDENT),
    FOREIGN KEY(ID_COURSE_FK) REFERENCES TB_COURSE(ID_COURSE)

);

--classroom_Student
CREATE  TABLE TB_CLASSROOM_STUDENT(
    ID_CLASSROOM_STUDENT INT,

    ID_STUDENT_FK INT,
    ID_CLASSROOM_FK INT,

    PRIMARY KEY(ID_STUDENT_FK, ID_CLASSROOM_FK),
    FOREIGN KEY(ID_STUDENT_FK) REFERENCES TB_STUDENT(ID_STUDENT),
    FOREIGN KEY(ID_CLASSROOM_FK) REFERENCES TB_CLASSROOM(ID_CLASSROOM)
);

--Student_Invoice
CREATE TABLE TB_STUDENT_INVOICE(
    ID_STUDENT_INVOICE INT,

    ID_STUDENT_FK INT,
    ID_INVOICE_FK INT,

    PRIMARY KEY(ID_STUDENT_FK, ID_INVOICE_FK),
    FOREIGN KEY(ID_STUDENT_FK) REFERENCES TB_STUDENT(ID_STUDENT),
    FOREIGN KEY(ID_INVOICE_FK) REFERENCES TB_INVOICE(ID_INVOICE)
);

--Subject_Course
CREATE TABLE TB_SUBJECT_COURSE(
    ID_SUBJECT_COURSE INT,

    ID_SUBJECT_FK INT,
    ID_COURSE_FK INT,

    PRIMARY KEY(ID_SUBJECT_FK, ID_COURSE_FK),
    FOREIGN KEY(ID_SUBJECT_FK) REFERENCES TB_SUBJECT (ID_SUBJECT),
    FOREIGN KEY(ID_COURSE_FK) REFERENCES TB_COURSE (ID_COURSE)
);

--Subject_Professor
CREATE TABLE TB_SUBJECT_PROFESSOR(
    ID_SUBJECT_PROFESSOR INT,

    ID_SUBJECT_FK INT,
    ID_PROFESSOR_FK INT,

    PRIMARY KEY(ID_SUBJECT_FK, ID_PROFESSOR_FK),
    FOREIGN KEY(ID_SUBJECT_FK) REFERENCES TB_SUBJECT(ID_SUBJECT),
    FOREIGN KEY(ID_PROFESSOR_FK) REFERENCES TB_PROFESSOR(ID_PROFESSOR)
);

--Subject_Student
CREATE TABLE TB_SUBJECT_STUDENT(
    ID_SUBJECT_STUDENT INT,

    ID_SUBJECT_FK INT,
    ID_STUDENT_FK INT,

    PRIMARY KEY(ID_SUBJECT_FK, ID_STUDENT_FK),
    FOREIGN KEY(ID_SUBJECT_FK)REFERENCES TB_SUBJECT(ID_SUBJECT),
    FOREIGN KEY(ID_STUDENT_FK)REFERENCES TB_STUDENT(ID_STUDENT)
);